### ISSUE TITLE
Create various folders for repository layout

### ISSUE THREAD

**Issue by daniel-utilityapi** [carbon-data-specification/Customer-Data#1]
* [x] `/meetings/` - for holding meeting minutes and assets
* [x] `/specifications/` - for the actual specifications to be created
* [x] `/docs/` - for the github pages website
* [ ] `/tests/` - for testing code

**Comment by jpradocueva** [comment]
@daniel-utilityapi this implies that each working group will have its own GitHub pages (that's ok). Are you also considering GitHub pages for Carbon Data Specifications as an Organization?

**Comment by daniel-utilityapi** [comment]
@jpradocueva yep, we discussed it at the last working group meeting (will be in the minutes when I add them to this repo).

The current plan is to have a customer data specific website, but it can link to or be part of a larger CDS set of websites if the other working group or strategy groups make their own, too.

**Comment by daniel-utilityapi** [comment]
Placeholder folders created! Didn't create the `/tests` folder since we're not sure yet what will go in there.
