### ISSUE TITLE
Create server discovery spec draft ("Server Metadata")

### ISSUE THREAD

**Issue by daniel-utilityapi** [carbon-data-specification/Customer-Data#15]
This is the specification describing how customer data sources (e.g. utilities) disclose what standardized functionality they offer.

* [x] Write summary overview with example
    * Source: https://github.com/daniel-utilityapi/Customer-Data/blob/issue_15_server_metadata/website/specs/cdsc-wg1-01/overview.md
    * Render: https://daniel-utilityapi.github.io/Customer-Data/specs/cdsc-wg1-01/overview
* [x] Review summary overview and example with working group
* [x] Write specification draft
    * Source: https://github.com/daniel-utilityapi/Customer-Data/blob/issue_15_server_metadata/specifications/cdsc-wg1-01.md
    * Render: https://daniel-utilityapi.github.io/Customer-Data/specs/cdsc-wg1-01
* [x] Open pull request for specification draft
* [ ] Review pull request with working group
* [ ] Update based on feedback
* [ ] Merge when consensus is obtained

**Comment by ssuffian** [comment]
This looks really good and reads really clearly. Excited to get more into the details regarding the Customer Data spec. Hallie's comments have me wondering where the line is between the Power System Data Working Group and this one. Would utilities be willing to provide the node that a customer is on, so that it could get linked to the Power System data?

**Comment by daniel-utilityapi** [comment]
Discussed the example at the [2022-08-25 meeting](https://github.com/carbon-data-specification/Customer-Data/blob/main/meetings/2022-08-25_meeting_minutes.md)

**Comment by daniel-utilityapi** [comment]
An update, I finally got an initial draft of the specification done.

Website render: https://daniel-utilityapi.github.io/Customer-Data/specs/cdsc-wg1-01/
Markdown in repo: https://github.com/daniel-utilityapi/Customer-Data/blob/main/specifications/cdsc-wg1-01.md

**Comment by daniel-utilityapi** [comment]
This issue has been moved to https://github.com/carbon-data-specification/Connectivity/issues/2
